--SET IDENTITY_INSERT [dbo].[Genre] ON
--INSERT INTO	[dbo].[Genre]
--		([Id], [Title])
--VALUES	(1, N'Action'),
--		(2, N'Animation'),
--		(3, N'Drama'),
--		(4, N'Musical'),
--		(5, N'Sci-Fi'),
--		(6, N'Thriller')
--SET IDENTITY_INSERT [dbo].[Genre] OFF